In [1]:
import numpy as np

Print the reverse NumPy array with type float.

In [2]:
numpy_arr = np.array([1,2,3,4,-8,-10], dtype= np.float16)
np.flip(numpy_arr)

array([-10.,  -8.,   4.,   3.,   2.,   1.], dtype=float16)

In [3]:
numpy_arr = np.array([1,2,3,4,-8,-10], dtype= np.float16)
np.array(numpy_arr[::-1], float)

array([-10.,  -8.,   4.,   3.,   2.,   1.])

Print the X NumPy array.

In [4]:
a1 = np.arange(1,10)
np.reshape(a1, (3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

3 3 3

In [5]:
a2 = np.zeros((3,3,3),dtype=int)
a3 = np.ones((3,3,3),dtype=int)
print(a2)
print(a3)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


Your task is to print the transpose and flatten results

In [6]:
a5 = np.arange(1,5)
a6 = np.reshape(a5,(2,2))
a6 = np.transpose(a6)
print(a6)
a5.flatten()

[[1 3]
 [2 4]]


array([1, 2, 3, 4])

Your task is to print an array of size X with its main diagonal elements as 's and 's everywhere else.

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Your task is to print the ,  and  of all the elements of 
1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
Find the floor, ceiling (round off), nearest integer

In [9]:
a7 = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print(np.floor(a7))
print(np.ceil(a7))
print(np.rint(a7))

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


Divide / Multiply 

In [ ]:
a8 = np.arange(10)
np.divide(a8,2)