In [2]:
import numpy as np

Create one dimensional array between 1 to 15 and change to 3 rows x 5 columns

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


Extract all odd numbers from above array

array([ 1,  3,  5,  7,  9, 11, 13])

Replace all even numbers in the original array with -1

[[-1  1 -1  3 -1]
 [ 5 -1  7 -1  9]
 [-1 11 -1 13 -1]]


Replace even odd numbers in arr with -1 without changing arr (Tip: Use Where)

[[-1  1 -1  3 -1]
 [ 5 -1  7 -1  9]
 [-1 11 -1 13 -1]]


array([[-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1]])

Create 2 arrays & Get the common items between a & b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

array([2, 4])

Remove all in b from a
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

array([1, 2, 3, 4])

How to find the most frequent value in an array? 
np.array([11,2,4,15,16,5,6])

Find the unique rows in the data
np.array([[1,8,3,3,4], [1,8,9,9,4], [1,8,3,3,4]])