Import the numpy library
Check the Version of the numpy

In [1]:
import numpy as np

Create a 1D array of numbers from 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create array of numbers between 10 to 30

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

Create array of numbers between 10 to 30 with multiples of 2 and find the type of array 

[10 12 14 16 18 20 22 24 26 28]
<class 'numpy.ndarray'>


Create array between 1 to 10 as float broken by 8 equal parts
Hint: linspace

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

Create a 3×3 numpy array of all True’s
Hint: full

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Find the shape of the array created above

(3, 3)

Create one dimensional array between 1 to 15 and change to 3 rows x 5 columns

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Remove all rows in a numpy array that contain non-numeric values
x = np.array([[1,2,3], [4,5,np.nan], [7,8,9], [True, False, True]])

[[1. 2. 3.]
 [7. 8. 9.]
 [1. 0. 1.]]
