In [1]:
import numpy as np

In [6]:
data = np.genfromtxt('unique.txt', delimiter=',',dtype=[int,'U2'],names=True)

In [7]:
type(data)

numpy.ndarray

In [9]:
data['C1']

array([6, 4, 2, 6, 8, 4])

In [11]:
unique, index = np.unique(data['C1'],return_index=True)

In [12]:
unique

array([2, 4, 6, 8])

In [13]:
index

array([2, 1, 0, 4], dtype=int64)

In [14]:
data[index]

array([(2, ' C'), (4, ' B'), (6, ' A'), (8, ' E')],
      dtype=[('C1', '<i4'), ('C2', '<U2')])

In [16]:
sorted = np.sort(data, axis=1)
sorted

<function ndarray.sort>